### ISSUE TITLE
Needs update to version 4.1.0

### ISSUE THREAD

**Issue by ebkalderon** [flathub/im.gitter.Gitter#3]
Not exactly sure where to properly report this, but there is a new Linux version of the Gitter app (4.1.0) available which fixes, among other things, the broken UI scaling on high-DPI monitors from the 3.x version of the app (https://gitlab.com/gitlab-org/gitter/desktop/issues/207). It would be great if this package could be bumped so updates can be pushed out to Flatpak users.

**Comment by ghisvail** [comment]
It's on my to-do list for the week.

Le mar. 5 juin 2018 à 09:08, Eyal Kalderon <notifications@github.com> a
écrit :

**Comment by ghisvail** [comment]
@ebkalderon Done. Could you test it please?

**Comment by ghisvail** [comment]
Works on my end. Closing.

**Comment by ebkalderon** [comment]
@ghisvail Good to hear! Thanks for testing it. Sorry I couldn't test it; I'm still at work right now.
